# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs


name: Node.js
      
on:
  push:
    branches: [ "main" ]
env:
  REACT_APP_BASE_URL: https://api.stutz.co.il
  
jobs:
  build:


    runs-on: self-hosted
    defaults:
      run:
        working-directory: 'clients' # Here the path to the folder where package-lock.json is located.
    strategy:
      matrix:
        node-version: [16.x] # Are you are missing this specification?
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json' # THIS PATTERN did the trick for me.
 
    - run: npm install
    - run: CI=false npm run build --if-present
    

    
# name: Node.js CI

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   build:


#     runs-on: self-hosted
#     defaults:
#       run:
#         working-directory: 'clients' # Here the path to the folder where package-lock.json is located.
#     strategy:
#       matrix:
#         node-version: [16.x] # Are you are missing this specification?
        
#     steps:
#      # Pipe Frontend
     
#     - name: Install dependencies
#       working-directory: ./server
#       run: npm install
      
#     - name: Restart Server
#       working-directory: ./server
#       run: pm2 reload all      
      
      
#     - name: Install dependencies
#       working-directory: ./clients
#       run: npm install
    
#     - name: Making Build
#       working-directory: ./clients
#       run: npm run build --if-present
      
 
 
